spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB1
    username: root
    password: sUdarsh@11
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8088