spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/week9
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8088

application:
  name: image-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka